
---
- hosts: localhost
  connection: local
  gather_facts: yes
  become: yes
  pre_tasks:
    - name: install packages for testing under packer
      yum:
        name: [ 'selinux-policy',
            'libselinux-python',
            'openssh-server',
            'which',
            'python-jmespath' ]
        state: present
  roles:
    - base
    # - role: RHEL7-CIS
    #   vars:
    #     rhel7cis_rule_1_1_1_8: false
    #     rhel7cis_rhnsd_required: false
